### ISSUE TITLE
Alert Dashborad

### ISSUE THREAD

**Issue by mango19b** [alekssako/grafana-dashboards#1]
Have a dashboard or solution for discussing alerting ?

**Comment by alekssako** [comment]
I have integrated it with [AlertManager](https://prometheus.io/docs/alerting/alertmanager/) and [prom2teams](https://github.com/idealista/prom2teams) for alerting in MS-TEAMS.

AlertManager config: 
```yaml
global:
  smtp_smarthost: 'smtp.mailtrap.io:2525'
  smtp_from: 'Alert Manager <xxxxxx-xxxxxxxxx@inbox.mailtrap.io>'
  smtp_auth_username: 'xxxxxxxxxxx'
  smtp_auth_password: 'xxxxxxxxxxx'

templates:
- '/etc/alertmanager/template/*.tmpl'
route:
  group_by: ['alertname', 'priority']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 12m
  receiver: DevOps
receivers:
- name: 'DevOps'
  email_configs:
  - to: 'xxxxx@domain.com'
  - to: 'yyyyy@domain.com'
  webhook_configs:
  - url: http://prom2teams-url:8089
    send_resolved: true
```

Prom2Teams :
- config.ini

```ini
[HTTP Server]
Host: 0.0.0.0
Port: 8089
[Microsoft Teams]
Connector: https://outlook.office.com/webhook/xxxxxxxxx/TeamFoundationServer/xxxxx/xxxxxxx
[Log]
Level: DEBUG
Path: /var/log/prom2teams/prom2teams.log
[Group Alerts]
Field: name
```

- uwsgi-config.ini
```ini
[uwsgi]
socket = 0.0.0.0:8089
protocol = http
env = APP_ENVIRONMENT=pro
env = APP_CONFIG_FILE=/etc/prom2teams/config.ini
logdate = True
logto = /var/log/prom2teams/uwsgi.log
vacuum = True
max-requests = 1000
master = True
enable-threads = True
processes = 5
threads = 10
vhost = True
```

Prometheus config : 
```yaml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager-url-or-ip:9093']
rule_files:
  - "rules/alert.rules.yml"
```
Alert Rules: have a look in here : [prometheus alert rules](https://awesome-prometheus-alerts.grep.to/rules.html)
